input_file: yourinput.json
cache_file: null
output_file: youroutput.json


convert_to_json: True

task_name:
  - criteria_v0.1

model_name: openai/gpt-5-mini
endpoints:
  - api_base: ""
    api_key: "YOUR_OPENAI_API_KEY "
parallel: 8
temperature: 0.0
max_token: 4096
api_type: openai
max_retry: 3
retry_sleep: 5
error_output: $ERROR$